config/routes.rb
Blanks::Application.routes.draw do |map|
  resources :items
  root :to => "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  scope :gildan_tees, order("items.hex_code ASC").where("mill_name = 'Gildan'").where("items.description like '%T-Shirt%'").where("style_number = '2000G'")
  
  def self.gildan_tees_by_color
    t = self.gildan_tees.uniq_by {|t| t.description}.reverse
    t.group_by {|t| t.color_name}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.xml
  def index
    @gildan_tees_by_color = Item.gildan_tees_by_color

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(@item, :notice => 'Item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :item_number %><br />
    <%= f.text_field :item_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :features %><br />
    <%= f.text_area :features %>
  </div>
  <div class="field">
    <%= f.label :p1_pricing %><br />
    <%= f.text_field :p1_pricing %>
  </div>
  <div class="field">
    <%= f.label :p2_pricing %><br />
    <%= f.text_field :p2_pricing %>
  </div>
  <div class="field">
    <%= f.label :p4_pricing %><br />
    <%= f.text_field :p4_pricing %>
  </div>
  <div class="field">
    <%= f.label :style_code %><br />
    <%= f.text_field :style_code %>
  </div>
  <div class="field">
    <%= f.label :size_name %><br />
    <%= f.text_field :size_name %>
  </div>
  <div class="field">
    <%= f.label :size_category %><br />
    <%= f.text_field :size_category %>
  </div>
  <div class="field">
    <%= f.label :size_code %><br />
    <%= f.text_field :size_code %>
  </div>
  <div class="field">
    <%= f.label :color_name %><br />
    <%= f.text_field :color_name %>
  </div>
  <div class="field">
    <%= f.label :hex_code %><br />
    <%= f.text_field :hex_code %>
  </div>
  <div class="field">
    <%= f.label :color_code %><br />
    <%= f.text_field :color_code %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :detail_image_url %><br />
    <%= f.text_field :detail_image_url %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :retail_price %><br />
    <%= f.text_field :retail_price %>
  </div>
  <div class="field">
    <%= f.label :style_number %><br />
    <%= f.text_field :style_number %>
  </div>
  <div class="field">
    <%= f.label :gtin_number %><br />
    <%= f.text_field :gtin_number %>
  </div>
  <div class="field">
    <%= f.label :max_inventory %><br />
    <%= f.text_field :max_inventory %>
  </div>
  <div class="field">
    <%= f.label :closeout %><br />
    <%= f.text_field :closeout %>
  </div>
  <div class="field">
    <%= f.label :mill_name %><br />
    <%= f.text_field :mill_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<table width="100%">
<% @gildan_tees_by_color.each do |color, tees| %>
  <tr>
    <td style="background:#<%= tees.first.hex_code %>;height:2em;color:#fff;">
      <%= color.humanize %>
    </td>
  </tr>
<% end %>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @item.company %>
</p>

<p>
  <b>Item number:</b>
  <%= @item.item_number %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Features:</b>
  <%= @item.features %>
</p>

<p>
  <b>P1 pricing:</b>
  <%= @item.p1_pricing %>
</p>

<p>
  <b>P2 pricing:</b>
  <%= @item.p2_pricing %>
</p>

<p>
  <b>P4 pricing:</b>
  <%= @item.p4_pricing %>
</p>

<p>
  <b>Style code:</b>
  <%= @item.style_code %>
</p>

<p>
  <b>Size name:</b>
  <%= @item.size_name %>
</p>

<p>
  <b>Size category:</b>
  <%= @item.size_category %>
</p>

<p>
  <b>Size code:</b>
  <%= @item.size_code %>
</p>

<p>
  <b>Color name:</b>
  <%= @item.color_name %>
</p>

<p>
  <b>Hex code:</b>
  <%= @item.hex_code %>
</p>

<p>
  <b>Color code:</b>
  <%= @item.color_code %>
</p>

<p>
  <b>Weight:</b>
  <%= @item.weight %>
</p>

<p>
  <b>Domain:</b>
  <%= @item.domain %>
</p>

<p>
  <b>Detail image url:</b>
  <%= @item.detail_image_url %>
</p>

<p>
  <b>Image url:</b>
  <%= @item.image_url %>
</p>

<p>
  <b>Retail price:</b>
  <%= @item.retail_price %>
</p>

<p>
  <b>Style number:</b>
  <%= @item.style_number %>
</p>

<p>
  <b>Gtin number:</b>
  <%= @item.gtin_number %>
</p>

<p>
  <b>Max inventory:</b>
  <%= @item.max_inventory %>
</p>

<p>
  <b>Closeout:</b>
  <%= @item.closeout %>
</p>

<p>
  <b>Mill name:</b>
  <%= @item.mill_name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blanks</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>